name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t jamesentenia/simple-website-docker-image:latest .

      - name: Push Docker Image
        run: docker push jamesentenia/simple-website-docker-image:latest

      - name: Deploy to ECS
        run: |
          # Update the ECS Service to use the Task Definition from the file
          aws ecs update-service --cluster james-ecs-cluster --service ecs-service \
            --task-definition file://.github/workflows/td.json

